daemon off;

events {}

http {
    server {
        listen 443 ssl;
        server_name chess42.fr;

        ssl_certificate     /etc/ssl/certs/selfsigned-cert.pem;
        ssl_certificate_key /etc/ssl/private/private-key.pem;

        ssl_protocols TLSv1.2;

        root /var/www/html;
        index index.php;

        location / {
            try_files $uri $uri/ /index.php;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}
