daemon off;

events {}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 443 ssl;
        server_name chess42.fr;

        ssl_certificate     /etc/ssl/certs/selfsigned-cert.pem;
        ssl_certificate_key /etc/ssl/private/private-key.pem;

        ssl_protocols TLSv1.2;

        root /usr/share/nginx/html;  # Angular build
        index index.html;

        location / {
            # Sert Angular SPA correctement
            try_files $uri $uri/ /index.html;
        }
    }
}