services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - transcendence_network

  nginx:
    build:
      context: ./requirements
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    env_file:
      - .env
    ports:
      - "80:80"
      - "${NGINX_PORT}:443"
    volumes:
      - ./data:/var/www/html
    restart: always
    depends_on:
      - nodejs
    networks:
      - transcendence_network

  nodejs:
    build: ./requirements/nodejs
    container_name: nodejs
    env_file:
      - .env
    restart: always
    volumes:
      - ./requirements/nodejs/src:/app/src
      - vite_cache:/app/node_modules/.vite
    ports:
      - "${APP_PORT}:3000"
      - "${VITE_PORT}:5173"
    networks:
      - transcendence_network

angular:
  build: ./requirements/angular
  container_name: angular
  volumes:
    - ./requirements/angular/src:/app/src  # hot-reload
  networks:
    - transcendence_network

  python:
    build: ./requirements/python
    container_name: python
    env_file:
      - .env
    networks:
      - transcendence_network      

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/db_data
  vite_cache:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/${LOGIN}/data/vite_cache

networks:
  transcendence_network:
    driver: bridge
